sudo: required
dist: trusty

script:
  - ls -lah
  - docker-compose up -d dbbackup
  - docker-compose ps
  - docker exec dockerpgbackups_dbbackup_1 ls
  - docker exec dockerpgbackups_dbbackup_1 date --set="2012-6-29 10:59.59 PM"
  - wait 4
  - ls -lah backups/*
  - if [[ ! -f "backups/2012/June/foo.dmp" ]]; then exit 1; fi
notifications:
      flowdock:
              secure: 4681cffa3cf2cd5b918706b115f0ce8a
  email:
    - tom.to.the.k@gmail.com
